/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Projects.Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EngineResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EngineResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Projects.Engine.EngineResource", typeof(EngineResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string ActionText_Accept {
            get {
                return ResourceManager.GetString("ActionText_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is added.
        /// </summary>
        internal static string ActionText_Add {
            get {
                return ResourceManager.GetString("ActionText_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was added to.
        /// </summary>
        internal static string ActionText_AddToTeam {
            get {
                return ResourceManager.GetString("ActionText_AddToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string ActionText_Closed {
            get {
                return ResourceManager.GetString("ActionText_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string ActionText_Create {
            get {
                return ResourceManager.GetString("ActionText_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string ActionText_Delete {
            get {
                return ResourceManager.GetString("ActionText_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted from.
        /// </summary>
        internal static string ActionText_DeletedFromTeam {
            get {
                return ResourceManager.GetString("ActionText_DeletedFromTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported.
        /// </summary>
        internal static string ActionText_Imported {
            get {
                return ResourceManager.GetString("ActionText_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was added to project team.
        /// </summary>
        internal static string ActionText_InviteToProject {
            get {
                return ResourceManager.GetString("ActionText_InviteToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved to trash.
        /// </summary>
        internal static string ActionText_MoveToTrash {
            get {
                return ResourceManager.GetString("ActionText_MoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was removed from project team.
        /// </summary>
        internal static string ActionText_RemoveFromProject {
            get {
                return ResourceManager.GetString("ActionText_RemoveFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumed.
        /// </summary>
        internal static string ActionText_Reopen {
            get {
                return ResourceManager.GetString("ActionText_Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string ActionText_Update {
            get {
                return ResourceManager.GetString("ActionText_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string ActionText_Uploaded {
            get {
                return ResourceManager.GetString("ActionText_Uploaded", resourceCulture);
            }
        }
    }
}
