/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Mail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailScriptResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailScriptResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Mail.Resources.MailScriptResource", typeof(MailScriptResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case the error persists, please read the {0}FAQ section{1} to learn more about the problem..
        /// </summary>
        public static string AccountCreationErrorGmailFooter {
            get {
                return ResourceManager.GetString("AccountCreationErrorGmailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account connection error.
        /// </summary>
        public static string AccountCreationErrorHeader {
            get {
                return ResourceManager.GetString("AccountCreationErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings.
        /// </summary>
        public static string AccountEdit {
            get {
                return ResourceManager.GetString("AccountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is connected using OAuth, editing is limited..
        /// </summary>
        public static string AccountNotificationText {
            get {
                return ResourceManager.GetString("AccountNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsLabel {
            get {
                return ResourceManager.GetString("AccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to activate %1?.
        /// </summary>
        public static string ActivateAccountShure {
            get {
                return ResourceManager.GetString("ActivateAccountShure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string AddAccountBtnLabel {
            get {
                return ResourceManager.GetString("AddAccountBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add your first mail account right now?.
        /// </summary>
        public static string AddAccountInfoQuestion {
            get {
                return ResourceManager.GetString("AddAccountInfoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t got any mail accounts connected to TeamLab Mail. Please add your mail account to start receiving and sending email messages..
        /// </summary>
        public static string AddAccountInfoText {
            get {
                return ResourceManager.GetString("AddAccountInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new account to start using TeamLab Mail..
        /// </summary>
        public static string AddAccountInfoTitle {
            get {
                return ResourceManager.GetString("AddAccountInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized. Authorize first..
        /// </summary>
        public static string AttachemntsUnauthorizedError {
            get {
                return ResourceManager.GetString("AttachemntsUnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some input params are invalid..
        /// </summary>
        public static string AttachmentsBadInputParamsError {
            get {
                return ResourceManager.GetString("AttachmentsBadInputParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to document is denied..
        /// </summary>
        public static string AttachmentsDocumentAccessDeniedError {
            get {
                return ResourceManager.GetString("AttachmentsDocumentAccessDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found or not exists on storage..
        /// </summary>
        public static string AttachmentsDocumentNotFoundError {
            get {
                return ResourceManager.GetString("AttachmentsDocumentNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty files not supported..
        /// </summary>
        public static string AttachmentsEmptyFileNotSupportedError {
            get {
                return ResourceManager.GetString("AttachmentsEmptyFileNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files may not be allowed by some services (f.e. Gmail)..
        /// </summary>
        public static string AttachmentsExecutableWarning {
            get {
                return ResourceManager.GetString("AttachmentsExecutableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The file size must not exceed %1 MB. The total size of all files should be no more than %2 MB..
        /// </summary>
        public static string AttachmentsLimitLabel {
            get {
                return ResourceManager.GetString("AttachmentsLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not found..
        /// </summary>
        public static string AttachmentsMessageNotFoundError {
            get {
                return ResourceManager.GetString("AttachmentsMessageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size of all attachments exceeds limit..
        /// </summary>
        public static string AttachmentsTotalLimitError {
            get {
                return ResourceManager.GetString("AttachmentsTotalLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error has happend. Try again later..
        /// </summary>
        public static string AttachmentsUnknownError {
            get {
                return ResourceManager.GetString("AttachmentsUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string AuthErrorPopupBody {
            get {
                return ResourceManager.GetString("AuthErrorPopupBody", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string AuthErrorPopupHeader {
            get {
                return ResourceManager.GetString("AuthErrorPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtnLabel {
            get {
                return ResourceManager.GetString("CancelBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose tag.
        /// </summary>
        public static string ChooseTag {
            get {
                return ResourceManager.GetString("ChooseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string CollapseAllLabel {
            get {
                return ResourceManager.GetString("CollapseAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your account settings. If you are sure your settings are correct, sign in to your mail provider to confirm any verification questions and then try again..
        /// </summary>
        public static string CorrectAccountRecommendation {
            get {
                return ResourceManager.GetString("CorrectAccountRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new CRM company.
        /// </summary>
        public static string CreateNewCRMCompany {
            get {
                return ResourceManager.GetString("CreateNewCRMCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new CRM person.
        /// </summary>
        public static string CreateNewCRMPerson {
            get {
                return ResourceManager.GetString("CreateNewCRMPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Contacts.
        /// </summary>
        public static string CRMContactsLabel {
            get {
                return ResourceManager.GetString("CRMContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to deactivate %1?.
        /// </summary>
        public static string DeactivateAccountShure {
            get {
                return ResourceManager.GetString("DeactivateAccountShure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete %1?.
        /// </summary>
        public static string DeleteAccountShure {
            get {
                return ResourceManager.GetString("DeleteAccountShure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this tag %1?.
        /// </summary>
        public static string DeleteTagShure {
            get {
                return ResourceManager.GetString("DeleteTagShure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of messages.
        /// </summary>
        public static string DeletionMessage {
            get {
                return ResourceManager.GetString("DeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery failed for message &quot;{subject}&quot;.{separator}Please, check your message recipients addresses and message format.  If you are sure your message is correct, check all the {account_name} account settings, and, if everything is correct, sign in to the mail service you use and confirm any verification questions, in case there are some. After then try again.{separator}In case the error persists, please read the {faq_link_open_tag}FAQ section{faq_link_close_tag} to learn more about the problem..
        /// </summary>
        public static string DeliveryFailurePopupBody {
            get {
                return ResourceManager.GetString("DeliveryFailurePopupBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message delivery failed.
        /// </summary>
        public static string DeliveryFailurePopupHeader {
            get {
                return ResourceManager.GetString("DeliveryFailurePopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose the first draft.
        /// </summary>
        public static string EmptyDraftsButton {
            get {
                return ResourceManager.GetString("EmptyDraftsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Draft section allows you to create and sort messages which you can send to different people later. Here you can tick the most important messages or delete the unnecessary ones..
        /// </summary>
        public static string EmptyDraftsDescription {
            get {
                return ResourceManager.GetString("EmptyDraftsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages to be displayed in this folder.
        /// </summary>
        public static string EmptyDraftsHeader {
            get {
                return ResourceManager.GetString("EmptyDraftsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose new letter.
        /// </summary>
        public static string EmptyInboxButton {
            get {
                return ResourceManager.GetString("EmptyInboxButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inbox section allows you to manage the messages you receive. Here you can see the correspondence history, tick the most important messages, group emails by categories using tags or delete the unnecessary ones..
        /// </summary>
        public static string EmptyInboxDescription {
            get {
                return ResourceManager.GetString("EmptyInboxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No letters recieved.
        /// </summary>
        public static string EmptyInboxHeader {
            get {
                return ResourceManager.GetString("EmptyInboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the first account.
        /// </summary>
        public static string EmptyScrAccountsButton {
            get {
                return ResourceManager.GetString("EmptyScrAccountsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up account to send, receive and keep your imails in order right on the portal. Get access to message history, contacts and files through any browser anytime, anywhere. Sort messages by your own tags..
        /// </summary>
        public static string EmptyScrAccountsDescription {
            get {
                return ResourceManager.GetString("EmptyScrAccountsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account is set up yet.
        /// </summary>
        public static string EmptyScrAccountsHeader {
            get {
                return ResourceManager.GetString("EmptyScrAccountsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to CRM.
        /// </summary>
        public static string EmptyScrCrmButton {
            get {
                return ResourceManager.GetString("EmptyScrCrmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contact list will contain all your clients from CRM.
        /// </summary>
        public static string EmptyScrCrmDescription {
            get {
                return ResourceManager.GetString("EmptyScrCrmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact list is empty.
        /// </summary>
        public static string EmptyScrCrmHeader {
            get {
                return ResourceManager.GetString("EmptyScrCrmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Mail Tag.
        /// </summary>
        public static string EmptyScrTagsButton {
            get {
                return ResourceManager.GetString("EmptyScrTagsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First create tag - then use them.
        /// </summary>
        public static string EmptyScrTagsDescription {
            get {
                return ResourceManager.GetString("EmptyScrTagsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags created.
        /// </summary>
        public static string EmptyScrTagsHeader {
            get {
                return ResourceManager.GetString("EmptyScrTagsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose new letter.
        /// </summary>
        public static string EmptySentButton {
            get {
                return ResourceManager.GetString("EmptySentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sent section allows you to manage the messages you send. Here you can tick the most important messages, group emails by categories using tags or delete the unnecessary ones..
        /// </summary>
        public static string EmptySentDescription {
            get {
                return ResourceManager.GetString("EmptySentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No letters sent yet.
        /// </summary>
        public static string EmptySentHeader {
            get {
                return ResourceManager.GetString("EmptySentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Spam section contains messages you identified as junk mail. Here you can delete emails, classify them as &apos;non-spam&apos; or clear the whole section..
        /// </summary>
        public static string EmptySpamDescription {
            get {
                return ResourceManager.GetString("EmptySpamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages to be displayed in this folder.
        /// </summary>
        public static string EmptySpamHeader {
            get {
                return ResourceManager.GetString("EmptySpamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trash section contains messages which were deleted. Here you can recover some emails or definitely delete them..
        /// </summary>
        public static string EmptyTrashDescription {
            get {
                return ResourceManager.GetString("EmptyTrashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages to be displayed in this folder.
        /// </summary>
        public static string EmptyTrashHeader {
            get {
                return ResourceManager.GetString("EmptyTrashHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already exists in TeamLab Mail..
        /// </summary>
        public static string ErrorAccountAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty field.
        /// </summary>
        public static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty From field.
        /// </summary>
        public static string ErrorEmptyFromField {
            get {
                return ResourceManager.GetString("ErrorEmptyFromField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty To field.
        /// </summary>
        public static string ErrorEmptyToField {
            get {
                return ResourceManager.GetString("ErrorEmptyToField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect address.
        /// </summary>
        public static string ErrorIncorrectAddress {
            get {
                return ResourceManager.GetString("ErrorIncorrectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect address.
        /// </summary>
        public static string ErrorIncorrectEmail {
            get {
                return ResourceManager.GetString("ErrorIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect address in from field.
        /// </summary>
        public static string ErrorIncorrectFromAddress {
            get {
                return ResourceManager.GetString("ErrorIncorrectFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error has happened!.
        /// </summary>
        public static string ErrorNotification {
            get {
                return ResourceManager.GetString("ErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has happened during account creation! Please, check your network connection, or ask for help your network or portal administrator!.
        /// </summary>
        public static string ErrorNotificationEx {
            get {
                return ResourceManager.GetString("ErrorNotificationEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has occurred while trying to open this message..
        /// </summary>
        public static string ErrorOpenMessage {
            get {
                return ResourceManager.GetString("ErrorOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refresh the page and try to open this message once again. In case the problem persists, please {0}contact our support team.{1}.
        /// </summary>
        public static string ErrorOpenMessageHelp {
            get {
                return ResourceManager.GetString("ErrorOpenMessageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag %1 already exists.
        /// </summary>
        public static string ErrorTagNameAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorTagNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to reconnect this account, please remove it first from the list of your connected accounts at the &apos;Settings &gt; Accounts Management&apos; page..
        /// </summary>
        public static string ExistAccountText {
            get {
                return ResourceManager.GetString("ExistAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing account.
        /// </summary>
        public static string ExistingAccountLabel {
            get {
                return ResourceManager.GetString("ExistingAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string ExpandAllLabel {
            get {
                return ResourceManager.GetString("ExpandAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export message to CRM.
        /// </summary>
        public static string ExportConversationPopupHeader {
            get {
                return ResourceManager.GetString("ExportConversationPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Export Error.
        /// </summary>
        public static string ExportFailurePopupHeader {
            get {
                return ResourceManager.GetString("ExportFailurePopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while exporting the message.
        /// </summary>
        public static string ExportFailurePopupName {
            get {
                return ResourceManager.GetString("ExportFailurePopupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message you are trying to export is already linked with the selected CRM item..
        /// </summary>
        public static string ExportFailurePopupText {
            get {
                return ResourceManager.GetString("ExportFailurePopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successed.
        /// </summary>
        public static string ExportMessageText {
            get {
                return ResourceManager.GetString("ExportMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another.
        /// </summary>
        public static string FilterAnotherGroup {
            get {
                return ResourceManager.GetString("FilterAnotherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string FilterByAuthor {
            get {
                return ResourceManager.GetString("FilterByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact types.
        /// </summary>
        public static string FilterByContactTypes {
            get {
                return ResourceManager.GetString("FilterByContactTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FilterByDate {
            get {
                return ResourceManager.GetString("FilterByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By period.
        /// </summary>
        public static string FilterByPeriod {
            get {
                return ResourceManager.GetString("FilterByPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string FilterBySubject {
            get {
                return ResourceManager.GetString("FilterBySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FilterByTitle {
            get {
                return ResourceManager.GetString("FilterByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string FilterChoose {
            get {
                return ResourceManager.GetString("FilterChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string FilterCompany {
            get {
                return ResourceManager.GetString("FilterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact types.
        /// </summary>
        public static string FilterContactType {
            get {
                return ResourceManager.GetString("FilterContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From sender.
        /// </summary>
        public static string FilterFromSender {
            get {
                return ResourceManager.GetString("FilterFromSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string FilterImportant {
            get {
                return ResourceManager.GetString("FilterImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string FilterPerson {
            get {
                return ResourceManager.GetString("FilterPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string FilterRead {
            get {
                return ResourceManager.GetString("FilterRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string FilterShowGroup {
            get {
                return ResourceManager.GetString("FilterShowGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To mail address.
        /// </summary>
        public static string FilterToMailAddress {
            get {
                return ResourceManager.GetString("FilterToMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        public static string FilterUnread {
            get {
                return ResourceManager.GetString("FilterUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With attachments.
        /// </summary>
        public static string FilterWithAttachments {
            get {
                return ResourceManager.GetString("FilterWithAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With opportunities.
        /// </summary>
        public static string FilterWithOpportunity {
            get {
                return ResourceManager.GetString("FilterWithOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With tags.
        /// </summary>
        public static string FilterWithTags {
            get {
                return ResourceManager.GetString("FilterWithTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fwd.
        /// </summary>
        public static string ForwardSubjectPrefix {
            get {
                return ResourceManager.GetString("ForwardSubjectPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarded message.
        /// </summary>
        public static string ForwardTitle {
            get {
                return ResourceManager.GetString("ForwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpCenterLabel {
            get {
                return ResourceManager.GetString("HelpCenterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always hide images from.
        /// </summary>
        public static string HideImagesLabel {
            get {
                return ResourceManager.GetString("HideImagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ImportAccountHeader {
            get {
                return ResourceManager.GetString("ImportAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ImportAccountRestrictLabel {
            get {
                return ResourceManager.GetString("ImportAccountRestrictLabel", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ImportAccountText {
            get {
                return ResourceManager.GetString("ImportAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string ImportantLabel {
            get {
                return ResourceManager.GetString("ImportantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ImportGmailAttention {
            get {
                return ResourceManager.GetString("ImportGmailAttention", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ImportProblemText {
            get {
                return ResourceManager.GetString("ImportProblemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string Kilobytes {
            get {
                return ResourceManager.GetString("Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link conversation with CRM.
        /// </summary>
        public static string LinkConversationPopupHeader {
            get {
                return ResourceManager.GetString("LinkConversationPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation linked.
        /// </summary>
        public static string LinkConversationText {
            get {
                return ResourceManager.GetString("LinkConversationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation Linking Error.
        /// </summary>
        public static string LinkFailurePopupHeader {
            get {
                return ResourceManager.GetString("LinkFailurePopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while linking the conversation to CRM.
        /// </summary>
        public static string LinkFailurePopupName {
            get {
                return ResourceManager.GetString("LinkFailurePopupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected CRM item is no longer available, or the connection has been lost. Please, verify the selected CRM item location and check your network connection. In case the error persists, please contact your portal administrator..
        /// </summary>
        public static string LinkFailurePopupText {
            get {
                return ResourceManager.GetString("LinkFailurePopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading attachments....
        /// </summary>
        public static string LoadingAttachments {
            get {
                return ResourceManager.GetString("LoadingAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox creation....
        /// </summary>
        public static string MailboxCreation {
            get {
                return ResourceManager.GetString("MailboxCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailBox update....
        /// </summary>
        public static string MailBoxUpdate {
            get {
                return ResourceManager.GetString("MailBoxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all recipient(s)`s mail.
        /// </summary>
        public static string MarkAllRecipientsLabel {
            get {
                return ResourceManager.GetString("MarkAllRecipientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all sender(s)`s mail.
        /// </summary>
        public static string MarkAllSendersLabel {
            get {
                return ResourceManager.GetString("MarkAllSendersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string Megabytes {
            get {
                return ResourceManager.GetString("Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string MessageNotSent {
            get {
                return ResourceManager.GetString("MessageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 more.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving of messages.
        /// </summary>
        public static string MovingMessages {
            get {
                return ResourceManager.GetString("MovingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add mail account.
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No further action is necessary..
        /// </summary>
        public static string NoActionText {
            get {
                return ResourceManager.GetString("NoActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No letters matching your filter can be displayed in this folder. Please select other filter options or clear filter to view all the contacts in this folder..
        /// </summary>
        public static string NoLettersFilterDescription {
            get {
                return ResourceManager.GetString("NoLettersFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No letters to be displayed for this filter here.
        /// </summary>
        public static string NoLettersFilterHeader {
            get {
                return ResourceManager.GetString("NoLettersFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no subject.
        /// </summary>
        public static string NoSubject {
            get {
                return ResourceManager.GetString("NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Spam.
        /// </summary>
        public static string NotSpamLabel {
            get {
                return ResourceManager.GetString("NotSpamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining default domain settings ....
        /// </summary>
        public static string ObtainingDefaultDomainSettings {
            get {
                return ResourceManager.GetString("ObtainingDefaultDomainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkBtnLabel {
            get {
                return ResourceManager.GetString("OkBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string OverallSelectAll {
            get {
                return ResourceManager.GetString("OverallSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all filtered.
        /// </summary>
        public static string OverallSelectAllFiltered {
            get {
                return ResourceManager.GetString("OverallSelectAllFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all in {0}.
        /// </summary>
        public static string OverallSelectAllInFolder {
            get {
                return ResourceManager.GetString("OverallSelectAllInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string PageHeaderDraft {
            get {
                return ResourceManager.GetString("PageHeaderDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string PageHeaderForward {
            get {
                return ResourceManager.GetString("PageHeaderForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string PageHeaderReply {
            get {
                return ResourceManager.GetString("PageHeaderReply", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string QuotaPopupBody {
            get {
                return ResourceManager.GetString("QuotaPopupBody", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string QuotaPopupHeader {
            get {
                return ResourceManager.GetString("QuotaPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        public static string ReadLabel {
            get {
                return ResourceManager.GetString("ReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove all letters from Spam?.
        /// </summary>
        public static string RemoveSpamQuestion {
            get {
                return ResourceManager.GetString("RemoveSpamQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove all letters from Trash?.
        /// </summary>
        public static string RemoveTrashQuestion {
            get {
                return ResourceManager.GetString("RemoveTrashQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re.
        /// </summary>
        public static string ReplySubjectPrefix {
            get {
                return ResourceManager.GetString("ReplySubjectPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CRM contacts matching your filter can be displayed on this page. Please select other filter options or clear filter to view all the CRM contacts..
        /// </summary>
        public static string ResetCrmContactsFilterDescription {
            get {
                return ResourceManager.GetString("ResetCrmContactsFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CRM contacts to be displayed for this filter here.
        /// </summary>
        public static string ResetCrmContactsFilterHeader {
            get {
                return ResourceManager.GetString("ResetCrmContactsFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset filter.
        /// </summary>
        public static string ResetFilterButton {
            get {
                return ResourceManager.GetString("ResetFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TeamLab contacts matching your filter can be displayed on this page. Please select other filter options or clear filter to view all the TeamLab contacts..
        /// </summary>
        public static string ResetTlContactsFilterDescription {
            get {
                return ResourceManager.GetString("ResetTlContactsFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TeamLab contacts to be displayed for this filter here.
        /// </summary>
        public static string ResetTlContactsFilterHeader {
            get {
                return ResourceManager.GetString("ResetTlContactsFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RestoreBtnLabel {
            get {
                return ResourceManager.GetString("RestoreBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring of messages.
        /// </summary>
        public static string RestoringMessages {
            get {
                return ResourceManager.GetString("RestoringMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving message.
        /// </summary>
        public static string SavingMessage {
            get {
                return ResourceManager.GetString("SavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been deactivated. Please, activate this account or select another one..
        /// </summary>
        public static string SendFromDeactivateAccount {
            get {
                return ResourceManager.GetString("SendFromDeactivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message.
        /// </summary>
        public static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message&apos;s been sent!.
        /// </summary>
        public static string SentMessageText {
            get {
                return ResourceManager.GetString("SentMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerLabel {
            get {
                return ResourceManager.GetString("ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string SpamLabel {
            get {
                return ResourceManager.GetString("SpamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SubjectLabel {
            get {
                return ResourceManager.GetString("SubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag creation....
        /// </summary>
        public static string TagCreation {
            get {
                return ResourceManager.GetString("TagCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name can&apos;t be empty.
        /// </summary>
        public static string TagNameCantBeEmpty {
            get {
                return ResourceManager.GetString("TagNameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported from CRM. You can&apos;t edit or delete this tag..
        /// </summary>
        public static string TagNotificationText {
            get {
                return ResourceManager.GetString("TagNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab Contacts.
        /// </summary>
        public static string TeamLabContactsLabel {
            get {
                return ResourceManager.GetString("TeamLabContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Uploader.
        /// </summary>
        public static string ToBasicUploader {
            get {
                return ResourceManager.GetString("ToBasicUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Uploader.
        /// </summary>
        public static string ToFlashUploader {
            get {
                return ResourceManager.GetString("ToFlashUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total contacts:.
        /// </summary>
        public static string TotalContacts {
            get {
                return ResourceManager.GetString("TotalContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total messages:.
        /// </summary>
        public static string TotalMessages {
            get {
                return ResourceManager.GetString("TotalMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgainButton {
            get {
                return ResourceManager.GetString("TryAgainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink from CRM.
        /// </summary>
        public static string UnlinkFromCRMPopupHeader {
            get {
                return ResourceManager.GetString("UnlinkFromCRMPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as unread.
        /// </summary>
        public static string UnreadLabel {
            get {
                return ResourceManager.GetString("UnreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With attachments.
        /// </summary>
        public static string WithAttachments {
            get {
                return ResourceManager.GetString("WithAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without tags.
        /// </summary>
        public static string WithoutTags {
            get {
                return ResourceManager.GetString("WithoutTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With tags.
        /// </summary>
        public static string WithTags {
            get {
                return ResourceManager.GetString("WithTags", resourceCulture);
            }
        }
    }
}
