/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Mail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailActionCompleteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailActionCompleteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Mail.Resources.MailActionCompleteResource", typeof(MailActionCompleteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The %folder% has been cleaned..
        /// </summary>
        internal static string clearFolder {
            get {
                return ResourceManager.GetString("clearFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected conversations have been deleted..
        /// </summary>
        internal static string deleteFilteredConversations {
            get {
                return ResourceManager.GetString("deleteFilteredConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected messages have been deleted..
        /// </summary>
        internal static string deleteFilteredMessages {
            get {
                return ResourceManager.GetString("deleteFilteredMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %count% conversations have been deleted..
        /// </summary>
        internal static string deleteManyConversations {
            get {
                return ResourceManager.GetString("deleteManyConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %count% messages have been deleted..
        /// </summary>
        internal static string deleteManyMessages {
            get {
                return ResourceManager.GetString("deleteManyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversation has been deleted..
        /// </summary>
        internal static string deleteOneConversation {
            get {
                return ResourceManager.GetString("deleteOneConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has been deleted..
        /// </summary>
        internal static string deleteOneMessage {
            get {
                return ResourceManager.GetString("deleteOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected converstaions have been moved to the %folder%..
        /// </summary>
        internal static string moveFilteredConversationsTo {
            get {
                return ResourceManager.GetString("moveFilteredConversationsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected messages have been moved to the %folder%..
        /// </summary>
        internal static string moveFilteredMessagesTo {
            get {
                return ResourceManager.GetString("moveFilteredMessagesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %count% conversations have been moved to the %folder%..
        /// </summary>
        internal static string moveManyConversationsTo {
            get {
                return ResourceManager.GetString("moveManyConversationsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %count% messages have been moved to the %folder%..
        /// </summary>
        internal static string moveManyMessagesTo {
            get {
                return ResourceManager.GetString("moveManyMessagesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversation has been moved to the %folder%..
        /// </summary>
        internal static string moveOneConversationTo {
            get {
                return ResourceManager.GetString("moveOneConversationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has been moved to the %folder%..
        /// </summary>
        internal static string moveOneMessageTo {
            get {
                return ResourceManager.GetString("moveOneMessageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected conversations have been restored..
        /// </summary>
        internal static string restoreFilteredConversations {
            get {
                return ResourceManager.GetString("restoreFilteredConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected messages have been restored..
        /// </summary>
        internal static string restoreFilteredMessages {
            get {
                return ResourceManager.GetString("restoreFilteredMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %count% conversations have been restored..
        /// </summary>
        internal static string restoreManyConversations {
            get {
                return ResourceManager.GetString("restoreManyConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %count% messages have been restored..
        /// </summary>
        internal static string restoreManyMessages {
            get {
                return ResourceManager.GetString("restoreManyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversation has been restored to the %folder%..
        /// </summary>
        internal static string restoreOneConversationTo {
            get {
                return ResourceManager.GetString("restoreOneConversationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has been restored to the %folder%..
        /// </summary>
        internal static string restoreOneMessageTo {
            get {
                return ResourceManager.GetString("restoreOneMessageTo", resourceCulture);
            }
        }
    }
}
