/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Studio.PublicResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceJS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceJS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Studio.PublicResources.ResourceJS", typeof(ResourceJS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation code cannot be empty.
        /// </summary>
        internal static string ActivateMobilePhoneEmptyCode {
            get {
                return ResourceManager.GetString("ActivateMobilePhoneEmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter mobile phone number.
        /// </summary>
        internal static string ActivateMobilePhoneEmptyPhoneNumber {
            get {
                return ResourceManager.GetString("ActivateMobilePhoneEmptyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the data you entered will be lost. Are you sure you want to continue?.
        /// </summary>
        internal static string CancelConfirmMessage {
            get {
                return ResourceManager.GetString("CancelConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string ClearFilterButton {
            get {
                return ResourceManager.GetString("ClearFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file.
        /// </summary>
        internal static string ErrorFileEmptyText {
            get {
                return ResourceManager.GetString("ErrorFileEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type isn&apos;t supported.
        /// </summary>
        internal static string ErrorFileTypeText {
            get {
                return ResourceManager.GetString("ErrorFileTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the wrong key..
        /// </summary>
        internal static string ErrorKeyActivation {
            get {
                return ResourceManager.GetString("ErrorKeyActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date must be later than birth date.
        /// </summary>
        internal static string ErrorMessage_InvalidDate {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add the same account and contact twice..
        /// </summary>
        internal static string ErrorMessageContactsDuplicated {
            get {
                return ResourceManager.GetString("ErrorMessageContactsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only enter up to 64 characters for this field..
        /// </summary>
        internal static string ErrorMessageLongField64 {
            get {
                return ResourceManager.GetString("ErrorMessageLongField64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that all user fields including first name, last name and email address are filled correctly.
        /// </summary>
        internal static string ImportContactsIncorrectFields {
            get {
                return ResourceManager.GetString("ImportContactsIncorrectFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string LoadingDescription {
            get {
                return ResourceManager.GetString("LoadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingProcessing {
            get {
                return ResourceManager.GetString("LoadingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Show.
        /// </summary>
        internal static string NeverShow {
            get {
                return ResourceManager.GetString("NeverShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Next.
        /// </summary>
        internal static string ShowNext {
            get {
                return ResourceManager.GetString("ShowNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The portal migration is successfully completed. Your portal is now available at.
        /// </summary>
        internal static string TransferPortalCompleted {
            get {
                return ResourceManager.GetString("TransferPortalCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t set up any password. You will be able to do it later using the &apos;Forgot your password?&apos; link at the portal login page. Are you sure you want to continue?.
        /// </summary>
        internal static string WizardCancelConfirmMessage {
            get {
                return ResourceManager.GetString("WizardCancelConfirmMessage", resourceCulture);
            }
        }
    }
}
