/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Bookmarking.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BookmarkingBusinessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookmarkingBusinessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Community.Bookmarking.Core.Resources.BookmarkingBusinessResources", typeof(BookmarkingBusinessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmark added to favorites.
        /// </summary>
        internal static string BookmarkAddedToFavouritesAction {
            get {
                return ResourceManager.GetString("BookmarkAddedToFavouritesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new bookmark created.
        /// </summary>
        internal static string BookmarkCreatedAction {
            get {
                return ResourceManager.GetString("BookmarkCreatedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmark removed from favorites.
        /// </summary>
        internal static string BookmarkRemovedAction {
            get {
                return ResourceManager.GetString("BookmarkRemovedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new comment added.
        /// </summary>
        internal static string CommentCreatedAction {
            get {
                return ResourceManager.GetString("CommentCreatedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment has been edited.
        /// </summary>
        internal static string CommentModifiedAction {
            get {
                return ResourceManager.GetString("CommentModifiedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment has been deleted.
        /// </summary>
        internal static string CommentRemovedAction {
            get {
                return ResourceManager.GetString("CommentRemovedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription to bookmarks.
        /// </summary>
        internal static string SubscriptionTypeNewBookmark {
            get {
                return ResourceManager.GetString("SubscriptionTypeNewBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription to comments.
        /// </summary>
        internal static string SubscriptionTypeNewComments {
            get {
                return ResourceManager.GetString("SubscriptionTypeNewComments", resourceCulture);
            }
        }
    }
}
