/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Api.Mail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Api.Mail.Resources.MailApiResource", typeof(MailApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some input params are invalid..
        /// </summary>
        internal static string AttachmentsBadInputParamsError {
            get {
                return ResourceManager.GetString("AttachmentsBadInputParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to document is denied..
        /// </summary>
        internal static string AttachmentsDocumentAccessDeniedError {
            get {
                return ResourceManager.GetString("AttachmentsDocumentAccessDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found or not exists on storage..
        /// </summary>
        internal static string AttachmentsDocumentNotFoundError {
            get {
                return ResourceManager.GetString("AttachmentsDocumentNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty files not supported..
        /// </summary>
        internal static string AttachmentsEmptyFileNotSupportedError {
            get {
                return ResourceManager.GetString("AttachmentsEmptyFileNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not found..
        /// </summary>
        internal static string AttachmentsMessageNotFoundError {
            get {
                return ResourceManager.GetString("AttachmentsMessageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size of all attachments exceeds limit..
        /// </summary>
        internal static string AttachmentsTotalLimitError {
            get {
                return ResourceManager.GetString("AttachmentsTotalLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error has happend. Try again later..
        /// </summary>
        internal static string AttachmentsUnknownError {
            get {
                return ResourceManager.GetString("AttachmentsUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message was created automatically by mail delivery software..
        /// </summary>
        internal static string DeliveryFailureAutomaticMessage {
            get {
                return ResourceManager.GetString("DeliveryFailureAutomaticMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your message.
        /// </summary>
        internal static string DeliveryFailureBtn {
            get {
                return ResourceManager.GetString("DeliveryFailureBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case the error persists, please read the {url_begin}FAQ section{url_end} to learn more about the problem..
        /// </summary>
        internal static string DeliveryFailureFAQInformation {
            get {
                return ResourceManager.GetString("DeliveryFailureFAQInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message headers follow.
        /// </summary>
        internal static string DeliveryFailureHeaders {
            get {
                return ResourceManager.GetString("DeliveryFailureHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery failed for message with subject &quot;{subject}&quot; from {date}..
        /// </summary>
        internal static string DeliveryFailureMessageIdentificator {
            get {
                return ResourceManager.GetString("DeliveryFailureMessageIdentificator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response from Smtp-server.
        /// </summary>
        internal static string DeliveryFailureReason {
            get {
                return ResourceManager.GetString("DeliveryFailureReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message could not be delivered to recipient(s).
        /// </summary>
        internal static string DeliveryFailureRecipients {
            get {
                return ResourceManager.GetString("DeliveryFailureRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your message recipients addresses and message format.  If you are sure your message is correct, check all the {account_name} account settings, and, if everything is correct, sign in to the mail service you use and confirm any verification questions, in case there are some. After then try again..
        /// </summary>
        internal static string DeliveryFailureRecommendations {
            get {
                return ResourceManager.GetString("DeliveryFailureRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Delivery Failure.
        /// </summary>
        internal static string DeliveryFailureSubject {
            get {
                return ResourceManager.GetString("DeliveryFailureSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field %1 is empty.
        /// </summary>
        internal static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect e-mail address in %1 field.
        /// </summary>
        internal static string ErrorIncorrectEmailAddress {
            get {
                return ResourceManager.GetString("ErrorIncorrectEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag %1 already exists.
        /// </summary>
        internal static string ErrorTagNameAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorTagNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name can&apos;t be empty.
        /// </summary>
        internal static string ErrorTagNameCantBeEmpty {
            get {
                return ResourceManager.GetString("ErrorTagNameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bcc.
        /// </summary>
        internal static string FieldNameBcc {
            get {
                return ResourceManager.GetString("FieldNameBcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc.
        /// </summary>
        internal static string FieldNameCc {
            get {
                return ResourceManager.GetString("FieldNameCc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string FieldNameFrom {
            get {
                return ResourceManager.GetString("FieldNameFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string FieldNameTo {
            get {
                return ResourceManager.GetString("FieldNameTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imap server connection timeout exceeded..
        /// </summary>
        internal static string ImapConnectionError {
            get {
                return ResourceManager.GetString("ImapConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAP response:.
        /// </summary>
        internal static string ImapResponse {
            get {
                return ResourceManager.GetString("ImapResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pop3 server connection timeout exceeded..
        /// </summary>
        internal static string Pop3ConnectionError {
            get {
                return ResourceManager.GetString("Pop3ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POP3 response:.
        /// </summary>
        internal static string Pop3Response {
            get {
                return ResourceManager.GetString("Pop3Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp server connection timeout exceeded..
        /// </summary>
        internal static string SmtpConnectionError {
            get {
                return ResourceManager.GetString("SmtpConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP response:.
        /// </summary>
        internal static string SmtRresponse {
            get {
                return ResourceManager.GetString("SmtRresponse", resourceCulture);
            }
        }
    }
}
