/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Files.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilesJSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilesJSResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Files.Resources.FilesJSResource", typeof(FilesJSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Settings.
        /// </summary>
        public static string AccessSettingsTitle {
            get {
                return ResourceManager.GetString("AccessSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string AceStatusEnum_Owner {
            get {
                return ResourceManager.GetString("AceStatusEnum_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        public static string AceStatusEnum_Read {
            get {
                return ResourceManager.GetString("AceStatusEnum_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Access.
        /// </summary>
        public static string AceStatusEnum_ReadWrite {
            get {
                return ResourceManager.GetString("AceStatusEnum_ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny Access.
        /// </summary>
        public static string AceStatusEnum_Restrict {
            get {
                return ResourceManager.GetString("AceStatusEnum_Restrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the import.
        /// </summary>
        public static string ButtonCancelImport {
            get {
                return ResourceManager.GetString("ButtonCancelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string ButtonFilterDocument {
            get {
                return ResourceManager.GetString("ButtonFilterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string ButtonFilterFile {
            get {
                return ResourceManager.GetString("ButtonFilterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string ButtonFilterFolder {
            get {
                return ResourceManager.GetString("ButtonFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string ButtonFilterImage {
            get {
                return ResourceManager.GetString("ButtonFilterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentations.
        /// </summary>
        public static string ButtonFilterPresentation {
            get {
                return ResourceManager.GetString("ButtonFilterPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheets.
        /// </summary>
        public static string ButtonFilterSpreadsheet {
            get {
                return ResourceManager.GetString("ButtonFilterSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more {0}.
        /// </summary>
        public static string ButtonShowMore {
            get {
                return ResourceManager.GetString("ButtonShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string ButtonShowMoreLoad {
            get {
                return ResourceManager.GetString("ButtonShowMoreLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more {0} of {1}.
        /// </summary>
        public static string ButtonShowMoreOf {
            get {
                return ResourceManager.GetString("ButtonShowMoreOf", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ButtonSortAuthor {
            get {
                return ResourceManager.GetString("ButtonSortAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ButtonSortModified {
            get {
                return ResourceManager.GetString("ButtonSortModified", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ButtonSortName {
            get {
                return ResourceManager.GetString("ButtonSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ButtonSortNew {
            get {
                return ResourceManager.GetString("ButtonSortNew", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ButtonSortSize {
            get {
                return ResourceManager.GetString("ButtonSortSize", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ButtonSortType {
            get {
                return ResourceManager.GetString("ButtonSortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete third party {0} from {1}?.
        /// </summary>
        public static string ConfirmDeleteThirdParty {
            get {
                return ResourceManager.GetString("ConfirmDeleteThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to empty the trash?.
        /// </summary>
        public static string ConfirmEmptyTrash {
            get {
                return ResourceManager.GetString("ConfirmEmptyTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave the current page. Downloading files will be interrupted..
        /// </summary>
        public static string ConfirmLeavePage {
            get {
                return ResourceManager.GetString("ConfirmLeavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the document?.
        /// </summary>
        public static string ConfirmRemoveFile {
            get {
                return ResourceManager.GetString("ConfirmRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the folder?.
        /// </summary>
        public static string ConfirmRemoveFolder {
            get {
                return ResourceManager.GetString("ConfirmRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these elements?.
        /// </summary>
        public static string ConfirmRemoveList {
            get {
                return ResourceManager.GetString("ConfirmRemoveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Documents.
        /// </summary>
        public static string CorporateFiles {
            get {
                return ResourceManager.GetString("CorporateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom format.
        /// </summary>
        public static string CustomFormat {
            get {
                return ResourceManager.GetString("CustomFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Archiving.
        /// </summary>
        public static string DescriptBulkdownload {
            get {
                return ResourceManager.GetString("DescriptBulkdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change data.
        /// </summary>
        public static string DescriptChangeInfo {
            get {
                return ResourceManager.GetString("DescriptChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string DescriptCopy {
            get {
                return ResourceManager.GetString("DescriptCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string DescriptCreate {
            get {
                return ResourceManager.GetString("DescriptCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading versions....
        /// </summary>
        public static string DescriptLoadVersion {
            get {
                return ResourceManager.GetString("DescriptLoadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking as Read.
        /// </summary>
        public static string DescriptMarkAsRead {
            get {
                return ResourceManager.GetString("DescriptMarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string DescriptMove {
            get {
                return ResourceManager.GetString("DescriptMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string DescriptRemove {
            get {
                return ResourceManager.GetString("DescriptRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string DescriptRename {
            get {
                return ResourceManager.GetString("DescriptRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating version.
        /// </summary>
        public static string DescriptSetVersion {
            get {
                return ResourceManager.GetString("DescriptSetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to import.
        /// </summary>
        public static string EmptyDataToImport {
            get {
                return ResourceManager.GetString("EmptyDataToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one folder/document to download.
        /// </summary>
        public static string EmptyListSelectedForDownload {
            get {
                return ResourceManager.GetString("EmptyListSelectedForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one document to import.
        /// </summary>
        public static string EmptyListSelectedForImport {
            get {
                return ResourceManager.GetString("EmptyListSelectedForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password.
        /// </summary>
        public static string ErrorMassage_AuthentificatedFalse {
            get {
                return ResourceManager.GetString("ErrorMassage_AuthentificatedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the fields to send a message.
        /// </summary>
        public static string ErrorMassage_EmptyField {
            get {
                return ResourceManager.GetString("ErrorMassage_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file.
        /// </summary>
        public static string ErrorMassage_EmptyFile {
            get {
                return ResourceManager.GetString("ErrorMassage_EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the conversion.
        /// </summary>
        public static string ErrorMassage_ErrorConvert {
            get {
                return ResourceManager.GetString("ErrorMassage_ErrorConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required to be filled in.
        /// </summary>
        public static string ErrorMassage_FieldsIsEmpty {
            get {
                return ResourceManager.GetString("ErrorMassage_FieldsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum file size is exceeded.
        /// </summary>
        public static string ErrorMassage_FileSize {
            get {
                return ResourceManager.GetString("ErrorMassage_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to download on mobile device.
        /// </summary>
        public static string ErrorMassage_MobileDownload {
            get {
                return ResourceManager.GetString("ErrorMassage_MobileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add you should login.
        /// </summary>
        public static string ErrorMassage_MustLogin {
            get {
                return ResourceManager.GetString("ErrorMassage_MustLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the previous download to complete or cancel it.
        /// </summary>
        public static string ErrorMassage_SecondDownload {
            get {
                return ResourceManager.GetString("ErrorMassage_SecondDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permission to perform the operation.
        /// </summary>
        public static string ErrorMassage_SecurityException {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not performed this action in this folder.
        /// </summary>
        public static string ErrorMassage_SecurityException_PrivateRoot {
            get {
                return ResourceManager.GetString("ErrorMassage_SecurityException_PrivateRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title can&apos;t contain any of the following characters: {0}.
        /// </summary>
        public static string ErrorMassage_SpecCharacter {
            get {
                return ResourceManager.GetString("ErrorMassage_SpecCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file with the name {0} already exists in the folder {1}..
        /// </summary>
        public static string FileAlreadyExist {
            get {
                return ResourceManager.GetString("FileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted.
        /// </summary>
        public static string FileConverted {
            get {
                return ResourceManager.GetString("FileConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting.
        /// </summary>
        public static string FileConverting {
            get {
                return ResourceManager.GetString("FileConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} documents with the same name already exist in the folder &apos;{1}&apos;. Overwrite the files?.
        /// </summary>
        public static string FilesAlreadyExist {
            get {
                return ResourceManager.GetString("FilesAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string FileUploading {
            get {
                return ResourceManager.GetString("FileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the file {0} was successfully restored.
        /// </summary>
        public static string FileVersionRecovery {
            get {
                return ResourceManager.GetString("FileVersionRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoxNet directory.
        /// </summary>
        public static string FolderTitleBoxNet {
            get {
                return ResourceManager.GetString("FolderTitleBoxNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropBox directory.
        /// </summary>
        public static string FolderTitleDropBox {
            get {
                return ResourceManager.GetString("FolderTitleDropBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google directory.
        /// </summary>
        public static string FolderTitleGoogle {
            get {
                return ResourceManager.GetString("FolderTitleGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDrive directory.
        /// </summary>
        public static string FolderTitleSkyDrive {
            get {
                return ResourceManager.GetString("FolderTitleSkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your Google Drive, Dropbox,  Box and SkyDrive accounts, or just import your files from Google Drive, Zoho or Box and have all documents in one place..
        /// </summary>
        public static string HelpContentConnectAccount {
            get {
                return ResourceManager.GetString("HelpContentConnectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this button to create new documents, spreadsheets and presentations directly on your portal..
        /// </summary>
        public static string HelpContentCreateFiles {
            get {
                return ResourceManager.GetString("HelpContentCreateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the file name to download and save the document to your hard disk drive..
        /// </summary>
        public static string HelpContentDownloadFiles {
            get {
                return ResourceManager.GetString("HelpContentDownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your files with other portal users or make them available to people outside your portal setting the appropriate access rights..
        /// </summary>
        public static string HelpContentShareFiles {
            get {
                return ResourceManager.GetString("HelpContentShareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the drop-down list to go to another TeamLab module or tool..
        /// </summary>
        public static string HelpContentSwitchModules {
            get {
                return ResourceManager.GetString("HelpContentSwitchModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the drop-down list to go to another TeamLab module or tool, or select People to add more users to your portal..
        /// </summary>
        public static string HelpContentSwitchModulesAd {
            get {
                return ResourceManager.GetString("HelpContentSwitchModulesAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this button to upload files: documents, spreadsheets, presentations etc stored on your hard disk drive..
        /// </summary>
        public static string HelpContentUploadFiles {
            get {
                return ResourceManager.GetString("HelpContentUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the file name to view the document, or use the pencil icon to open it for editing. For faster processing your file will be converted to the Office Open XML format..
        /// </summary>
        public static string HelpContentViewFiles {
            get {
                return ResourceManager.GetString("HelpContentViewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Your Account.
        /// </summary>
        public static string HelpTitleConnectAccount {
            get {
                return ResourceManager.GetString("HelpTitleConnectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Files.
        /// </summary>
        public static string HelpTitleCreateFiles {
            get {
                return ResourceManager.GetString("HelpTitleCreateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Your Files.
        /// </summary>
        public static string HelpTitleDownloadFiles {
            get {
                return ResourceManager.GetString("HelpTitleDownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Your Files.
        /// </summary>
        public static string HelpTitleShareFiles {
            get {
                return ResourceManager.GetString("HelpTitleShareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between Modules.
        /// </summary>
        public static string HelpTitleSwitchModules {
            get {
                return ResourceManager.GetString("HelpTitleSwitchModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Your Files.
        /// </summary>
        public static string HelpTitleUploadFiles {
            get {
                return ResourceManager.GetString("HelpTitleUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &amp; Edit Your Files.
        /// </summary>
        public static string HelpTitleViewFiles {
            get {
                return ResourceManager.GetString("HelpTitleViewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Box.Net.
        /// </summary>
        public static string ImportFromBoxNet {
            get {
                return ResourceManager.GetString("ImportFromBoxNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Google Docs.
        /// </summary>
        public static string ImportFromGoogle {
            get {
                return ResourceManager.GetString("ImportFromGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Zoho.
        /// </summary>
        public static string ImportFromZoho {
            get {
                return ResourceManager.GetString("ImportFromZoho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Progress.
        /// </summary>
        public static string ImportProgress {
            get {
                return ResourceManager.GetString("ImportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import is canceled.
        /// </summary>
        public static string InfoCancelImport {
            get {
                return ResourceManager.GetString("InfoCancelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; changed.
        /// </summary>
        public static string InfoChangeThirdParty {
            get {
                return ResourceManager.GetString("InfoChangeThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} copied elements.
        /// </summary>
        public static string InfoCopyGroup {
            get {
                return ResourceManager.GetString("InfoCopyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; copied.
        /// </summary>
        public static string InfoCopyItem {
            get {
                return ResourceManager.GetString("InfoCopyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link has been copied.
        /// </summary>
        public static string InfoCopyLink {
            get {
                return ResourceManager.GetString("InfoCopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file &apos;{0}&apos; is created.
        /// </summary>
        public static string InfoCrateFile {
            get {
                return ResourceManager.GetString("InfoCrateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file &apos;{0}&apos; is created in &apos;{1}&apos;.
        /// </summary>
        public static string InfoCrateFileIn {
            get {
                return ResourceManager.GetString("InfoCrateFileIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder &apos;{0}&apos; is created.
        /// </summary>
        public static string InfoCrateFolder {
            get {
                return ResourceManager.GetString("InfoCrateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import is completed.
        /// </summary>
        public static string InfoFinishImport {
            get {
                return ResourceManager.GetString("InfoFinishImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot copy the folder to its subfolder.
        /// </summary>
        public static string InfoFolderCopyError {
            get {
                return ResourceManager.GetString("InfoFolderCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot move the folder to its subfolder.
        /// </summary>
        public static string InfoFolderMoveError {
            get {
                return ResourceManager.GetString("InfoFolderMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the previous import to complete.
        /// </summary>
        public static string InfoImprotNotFinish {
            get {
                return ResourceManager.GetString("InfoImprotNotFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} moved elements.
        /// </summary>
        public static string InfoMoveGroup {
            get {
                return ResourceManager.GetString("InfoMoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; moved.
        /// </summary>
        public static string InfoMoveItem {
            get {
                return ResourceManager.GetString("InfoMoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is deleted.
        /// </summary>
        public static string InfoRemoveFile {
            get {
                return ResourceManager.GetString("InfoRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; is deleted.
        /// </summary>
        public static string InfoRemoveFolder {
            get {
                return ResourceManager.GetString("InfoRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was successfully deleted {0} from {1}.
        /// </summary>
        public static string InfoRemoveGroup {
            get {
                return ResourceManager.GetString("InfoRemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party &apos;{0}&apos; is deleted.
        /// </summary>
        public static string InfoRemoveThirdParty {
            get {
                return ResourceManager.GetString("InfoRemoveThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is renamed to &apos;{1}&apos;.
        /// </summary>
        public static string InfoRenameFile {
            get {
                return ResourceManager.GetString("InfoRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; is renamed to &apos;{1}&apos;.
        /// </summary>
        public static string InfoRenameFolder {
            get {
                return ResourceManager.GetString("InfoRenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; added to &apos;{1}&apos;.
        /// </summary>
        public static string InfoSaveThirdParty {
            get {
                return ResourceManager.GetString("InfoSaveThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements: {0}.
        /// </summary>
        public static string InfoSelectCount {
            get {
                return ResourceManager.GetString("InfoSelectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Drag the element(s) with the mouse to add to the folder.
        /// </summary>
        public static string InfoSelectingDescribe {
            get {
                return ResourceManager.GetString("InfoSelectingDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} documents are successfully uploaded.
        /// </summary>
        public static string InfoUploadedSuccess {
            get {
                return ResourceManager.GetString("InfoUploadedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string MyFiles {
            get {
                return ResourceManager.GetString("MyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original format.
        /// </summary>
        public static string OriginalFormat {
            get {
                return ResourceManager.GetString("OriginalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentations.
        /// </summary>
        public static string Presentations {
            get {
                return ResourceManager.GetString("Presentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project documents.
        /// </summary>
        public static string ProjectFiles {
            get {
                return ResourceManager.GetString("ProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreedsheets.
        /// </summary>
        public static string Spreedsheets {
            get {
                return ResourceManager.GetString("Spreedsheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Archiving.
        /// </summary>
        public static string TasksOperationBulkdownload {
            get {
                return ResourceManager.GetString("TasksOperationBulkdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string TasksOperationCopy {
            get {
                return ResourceManager.GetString("TasksOperationCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string TasksOperationDelete {
            get {
                return ResourceManager.GetString("TasksOperationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking as Read.
        /// </summary>
        public static string TasksOperationMarkAsRead {
            get {
                return ResourceManager.GetString("TasksOperationMarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operations.
        /// </summary>
        public static string TasksOperationMixed {
            get {
                return ResourceManager.GetString("TasksOperationMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string TasksOperationMove {
            get {
                return ResourceManager.GetString("TasksOperationMove", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ThirdPartyEditorCaption {
            get {
                return ResourceManager.GetString("ThirdPartyEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ThirdPartyEditorCaptionAppend {
            get {
                return ResourceManager.GetString("ThirdPartyEditorCaptionAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ({0}).
        /// </summary>
        public static string ThirdPartyGetToken {
            get {
                return ResourceManager.GetString("ThirdPartyGetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TitleCancel {
            get {
                return ResourceManager.GetString("TitleCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is currently being edited.
        /// </summary>
        public static string TitleEditingFile {
            get {
                return ResourceManager.GetString("TitleEditingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is currently being edited by: {0}.
        /// </summary>
        public static string TitleEditingFileBy {
            get {
                return ResourceManager.GetString("TitleEditingFileBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Presentation.
        /// </summary>
        public static string TitleNewFilePresentation {
            get {
                return ResourceManager.GetString("TitleNewFilePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Spreadsheet.
        /// </summary>
        public static string TitleNewFileSpreadsheet {
            get {
                return ResourceManager.GetString("TitleNewFileSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string TitleNewFileText {
            get {
                return ResourceManager.GetString("TitleNewFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string TitleNewFolder {
            get {
                return ResourceManager.GetString("TitleNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        public static string TitleSettingsCommon {
            get {
                return ResourceManager.GetString("TitleSettingsCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TitleSettingsHelp {
            get {
                return ResourceManager.GetString("TitleSettingsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect accounts.
        /// </summary>
        public static string TitleSettingsThirdParty {
            get {
                return ResourceManager.GetString("TitleSettingsThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version history:.
        /// </summary>
        public static string TitleVersionHistory {
            get {
                return ResourceManager.GetString("TitleVersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to box.com.
        /// </summary>
        public static string TypeTitleBoxNet {
            get {
                return ResourceManager.GetString("TypeTitleBoxNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dropbox.com.
        /// </summary>
        public static string TypeTitleDropBox {
            get {
                return ResourceManager.GetString("TypeTitleDropBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google.com.
        /// </summary>
        public static string TypeTitleGoogle {
            get {
                return ResourceManager.GetString("TypeTitleGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skydrive.com.
        /// </summary>
        public static string TypeTitleSkyDrive {
            get {
                return ResourceManager.GetString("TypeTitleSkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error....
        /// </summary>
        public static string UnknownErrorText {
            get {
                return ResourceManager.GetString("UnknownErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete.
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading ....
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0} files ({1}% done).
        /// </summary>
        public static string UploadingProgress {
            get {
                return ResourceManager.GetString("UploadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} Used.
        /// </summary>
        public static string UsedSize {
            get {
                return ResourceManager.GetString("UsedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
