/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Community.Wiki.Code.Patterns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WikiPatternResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WikiPatternResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Community.Wiki.Code.Patterns.WikiPatternResource", typeof(WikiPatternResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.New Wiki Page Added: &quot;$PageName&quot;:&quot;$URL&quot;
        ///
        ///$Date &quot;$UserName&quot;:&quot;$UserURL&quot; has created a new wiki page:
        ///
        ///$PagePreview
        ///
        ///&quot;Read More&quot;:&quot;$URL&quot;
        ///
        ///Your portal address: &quot;$__VirtualRootPath&quot;:&quot;$__VirtualRootPath&quot;
        ///
        ///&quot;Edit subscripion settings&quot;:&quot;$RecipientSubscriptionConfigURL&quot;.
        /// </summary>
        internal static string pattern_1 {
            get {
                return ResourceManager.GetString("pattern_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.Wiki Page Edited: &quot;$PageName&quot;:&quot;$URL&quot;
        ///
        ///$Date &quot;$UserName&quot;:&quot;$UserURL&quot; has edited the Wiki page:
        ///
        ///$PagePreview
        ///
        ///&quot;Read More&quot;:&quot;$URL&quot;
        ///
        ///Your portal address: &quot;$__VirtualRootPath&quot;:&quot;$__VirtualRootPath&quot;
        ///
        ///&quot;Edit subscripion settings&quot;:&quot;$RecipientSubscriptionConfigURL&quot;.
        /// </summary>
        internal static string pattern_2 {
            get {
                return ResourceManager.GetString("pattern_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.New Comment to Wiki Page &quot;$PageName&quot;:&quot;$URL&quot;
        ///
        ///$Date &quot;$UserName&quot;:&quot;$UserURL&quot; has added a comment to the Wiki page:
        ///
        ///$CommentBody
        ///
        ///&quot;Read More&quot;:&quot;$URL&quot;
        ///
        ///Your portal address: &quot;$__VirtualRootPath&quot;:&quot;$__VirtualRootPath&quot;
        ///
        ///&quot;Edit subscripion settings&quot;:&quot;$RecipientSubscriptionConfigURL&quot;.
        /// </summary>
        internal static string pattern_3 {
            get {
                return ResourceManager.GetString("pattern_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community. New Wiki Page Added: $PageName.
        /// </summary>
        internal static string subject_1 {
            get {
                return ResourceManager.GetString("subject_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community. Wiki Page Edited: $PageName.
        /// </summary>
        internal static string subject_2 {
            get {
                return ResourceManager.GetString("subject_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community. New Comment to Wiki Page: $PageName.
        /// </summary>
        internal static string subject_3 {
            get {
                return ResourceManager.GetString("subject_3", resourceCulture);
            }
        }
    }
}
