/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.CRM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRMSocialMediaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMSocialMediaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.CRM.Resources.CRMSocialMediaResource", typeof(CRMSocialMediaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog feed.
        /// </summary>
        public static string BlogFeed {
            get {
                return ResourceManager.GetString("BlogFeed", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be aware of what your clients think about your produce and brand in the social network. Simply link the twitter account with the contact and follow the tweet news feed right on your portal..
        /// </summary>
        public static string EmptyContentTwitterAccountsDescribe {
            get {
                return ResourceManager.GetString("EmptyContentTwitterAccountsDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No linked twitter accounts.
        /// </summary>
        public static string EmptyContentTwitterAccountsHeader {
            get {
                return ResourceManager.GetString("EmptyContentTwitterAccountsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string FindInSocialMedia {
            get {
                return ResourceManager.GetString("FindInSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string InformationProvidedBy {
            get {
                return ResourceManager.GetString("InformationProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link twitter account.
        /// </summary>
        public static string LinkTwitterAccount {
            get {
                return ResourceManager.GetString("LinkTwitterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NoAccountsHasBeenFound {
            get {
                return ResourceManager.GetString("NoAccountsHasBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NoCompaniesHasBeenFound {
            get {
                return ResourceManager.GetString("NoCompaniesHasBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string PleaseWaitForSearching {
            get {
                return ResourceManager.GetString("PleaseWaitForSearching", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ProfilesInSocialMedia {
            get {
                return ResourceManager.GetString("ProfilesInSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string Relate {
            get {
                return ResourceManager.GetString("Relate", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RelateAccountToContact {
            get {
                return ResourceManager.GetString("RelateAccountToContact", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RelateAvatar {
            get {
                return ResourceManager.GetString("RelateAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SearchInSocialMedia {
            get {
                return ResourceManager.GetString("SearchInSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
    }
}
