/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.UserControls.SocialMedia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SocialMediaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SocialMediaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.UserControls.SocialMedia.Resources.SocialMediaResource", typeof(SocialMediaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorFacebookAccountNotFound {
            get {
                return ResourceManager.GetString("ErrorFacebookAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorFacebookAPILimit {
            get {
                return ResourceManager.GetString("ErrorFacebookAPILimit", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorFacebookOAuth {
            get {
                return ResourceManager.GetString("ErrorFacebookOAuth", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorInternalServer {
            get {
                return ResourceManager.GetString("ErrorInternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorLinkedInUnauthorized {
            get {
                return ResourceManager.GetString("ErrorLinkedInUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterAccountNotFound {
            get {
                return ResourceManager.GetString("ErrorTwitterAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterConnectionFailure {
            get {
                return ResourceManager.GetString("ErrorTwitterConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterIsDown {
            get {
                return ResourceManager.GetString("ErrorTwitterIsDown", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterRateLimit {
            get {
                return ResourceManager.GetString("ErrorTwitterRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterUnauthorized {
            get {
                return ResourceManager.GetString("ErrorTwitterUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorUnknownTwitterAccount {
            get {
                return ResourceManager.GetString("ErrorUnknownTwitterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string MessageCount {
            get {
                return ResourceManager.GetString("MessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SocialMediaAccountNotFound {
            get {
                return ResourceManager.GetString("SocialMediaAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SocialMediaAccountNotFoundFacebook {
            get {
                return ResourceManager.GetString("SocialMediaAccountNotFoundFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SocialMediaAccountNotFoundLinkedIn {
            get {
                return ResourceManager.GetString("SocialMediaAccountNotFoundLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SocialMediaAccountNotFoundTwitter {
            get {
                return ResourceManager.GetString("SocialMediaAccountNotFoundTwitter", resourceCulture);
            }
        }
    }
}
