/* 
 * 
 * (c) Copyright Ascensio System Limited 2010-2014
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * http://www.gnu.org/licenses/agpl.html 
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Projects.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectsEnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectsEnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Projects.Core.Resources.ProjectsEnumResource", typeof(ProjectsEnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string EntityType_Comment {
            get {
                return ResourceManager.GetString("EntityType_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string EntityType_File {
            get {
                return ResourceManager.GetString("EntityType_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string EntityType_Message {
            get {
                return ResourceManager.GetString("EntityType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string EntityType_Milestone {
            get {
                return ResourceManager.GetString("EntityType_Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string EntityType_Project {
            get {
                return ResourceManager.GetString("EntityType_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask.
        /// </summary>
        public static string EntityType_SubTask {
            get {
                return ResourceManager.GetString("EntityType_SubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string EntityType_Task {
            get {
                return ResourceManager.GetString("EntityType_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string EntityType_Team {
            get {
                return ResourceManager.GetString("EntityType_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string EntityType_TimeSpend {
            get {
                return ResourceManager.GetString("EntityType_TimeSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string IssuePriority_High {
            get {
                return ResourceManager.GetString("IssuePriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Urgent.
        /// </summary>
        public static string IssuePriority_Immediate {
            get {
                return ResourceManager.GetString("IssuePriority_Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string IssuePriority_Low {
            get {
                return ResourceManager.GetString("IssuePriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string IssuePriority_Normal {
            get {
                return ResourceManager.GetString("IssuePriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string IssuePriority_Urgent {
            get {
                return ResourceManager.GetString("IssuePriority_Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string IssueStatus_Closed {
            get {
                return ResourceManager.GetString("IssueStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string IssueStatus_Fixed {
            get {
                return ResourceManager.GetString("IssueStatus_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string IssueStatus_New {
            get {
                return ResourceManager.GetString("IssueStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string IssueStatus_Open {
            get {
                return ResourceManager.GetString("IssueStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string IssueStatus_Rejected {
            get {
                return ResourceManager.GetString("IssueStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string MilestoneStatus_Closed {
            get {
                return ResourceManager.GetString("MilestoneStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Trash.
        /// </summary>
        public static string MilestoneStatus_Disable {
            get {
                return ResourceManager.GetString("MilestoneStatus_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string MilestoneStatus_Late {
            get {
                return ResourceManager.GetString("MilestoneStatus_Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string MilestoneStatus_Open {
            get {
                return ResourceManager.GetString("MilestoneStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billed.
        /// </summary>
        public static string PaymentStatus_Billed {
            get {
                return ResourceManager.GetString("PaymentStatus_Billed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Billed.
        /// </summary>
        public static string PaymentStatus_NotBilled {
            get {
                return ResourceManager.GetString("PaymentStatus_NotBilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Chargeable.
        /// </summary>
        public static string PaymentStatus_NotChargeable {
            get {
                return ResourceManager.GetString("PaymentStatus_NotChargeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ProjectStatus_Closed {
            get {
                return ResourceManager.GetString("ProjectStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ProjectStatus_Open {
            get {
                return ResourceManager.GetString("ProjectStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string ProjectStatus_Paused {
            get {
                return ResourceManager.GetString("ProjectStatus_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string TaskPriority_High {
            get {
                return ResourceManager.GetString("TaskPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string TaskPriority_Low {
            get {
                return ResourceManager.GetString("TaskPriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TaskPriority_Normal {
            get {
                return ResourceManager.GetString("TaskPriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string TaskStatus_Closed {
            get {
                return ResourceManager.GetString("TaskStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Trash.
        /// </summary>
        public static string TaskStatus_Disable {
            get {
                return ResourceManager.GetString("TaskStatus_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting start.
        /// </summary>
        public static string TaskStatus_NotAccept {
            get {
                return ResourceManager.GetString("TaskStatus_NotAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string TaskStatus_Open {
            get {
                return ResourceManager.GetString("TaskStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not classified.
        /// </summary>
        public static string TaskStatus_Unclassified {
            get {
                return ResourceManager.GetString("TaskStatus_Unclassified", resourceCulture);
            }
        }
    }
}
